# .github/workflows/build-windows.yml

name: Build Windows Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      # 第 1 步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第 2 步：设置 Node.js 环境
      # **重要：**将 node-version 升级到 22 以匹配依赖要求
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 第 3 步：安装项目依赖
      - name: Install dependencies
        run: npm install

      # 第 4 步：构建 Windows 安装程序
      # 现在 npm run build 会执行 npx electron-builder，确保命令能被找到
      - name: Build Windows installer
        run: npm run build -- --win --x64

      # 第 5 步：上传构建产物
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: stardps-windows-installer
          path: dist/*.exe
